config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :wikis
  resources :collaborators, only: [:create, :destroy]


  devise_for :users
  resources :charges, only: [:new, :create]
  resources :user_upgrades, only: [:edit]
  resources :user_downgrades, only: [:edit]
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
  

end

app/models/user.rb
class User < ActiveRecord::Base

  enum role: [:standard, :premium, :admin]
  after_initialize(:set_default_role, { if: :new_record? })


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :wikis
  has_many :collaborators, dependent: :destroy


  private
  def set_default_role
    self.role ||= :standard
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :collaborators
  has_many :wiki_collaborators, through: :collaborators, :source => :user


  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :private, default: false
  validates :user, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  private

  def user_not_authorized(exception)
    #flash[:alert] = "You are not authorized to perform this action."
    policy_name = exception.policy.class.to_s.underscore
    flash[:alert] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     # Where the real magic happens
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: Amount.default,
       description: "BigMoney Membership - #{current_user.email}",
       currency: 'usd'
     )

     flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
     #current_user.premium!
     redirect_to edit_user_upgrade_path(current_user) # or wherever
     #redirect_to root_path

     # Stripe will send back CardErrors, with friendly messages
     # when something goes wrong.
     # This `rescue block` catches and displays those errors.
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
   end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    #create an entry in the collaborator table
    #collaborator = @user.collaborator.build(wiki: wiki)

    @collaborator = Collaborator.new(collaborator_params)
    #@collaborator.user_id = params[:user_id]
    #@collaborator.wiki_id = params[:wiki_id]

    if @collaborator.save
      flash[:notice] = "You added a collaborator!"
      redirect_to :back
    else
      flash.now[:alert] = "There was an error saving the collaborator. Please try again."
      redirect_to :back
      end
  end


  def destroy
    @collaborator = Collaborator.where(:wiki_id => params[:id], :user_id => params[:user_id])
    if @collaborator.destroy_all
      flash[:notice] = "The collaborator was removed!"
      redirect_to :back
    else
      flash[:alert] = "Oops! Something happened and we weren't able to delete the collaborator."
      redirect_to :back
    end
  end

  private
  # Using a private method to encapsulate the permissible parameters
  def collaborator_params

    params.permit([:wiki_id, :user_id])

  end
end

app/controllers/user_downgrades_controller.rb
class UserDowngradesController < ApplicationController
  def edit
    current_user.standard!
    #make all private wikis public
    Wiki.where("user_id = ? and private = ?", current_user, true).update_all(:private => false)
    redirect_to root_path
  end
end

app/controllers/user_upgrades_controller.rb
class UserUpgradesController < ApplicationController
  def edit
    current_user.premium!
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    #@wikis = Wiki.all
    @wikis = policy_scope(Wiki)

  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "You created a new wiki!"
      redirect_to [@wiki]
    else
      flash[:alert] = "There was an error when we tried to save it. Try again."
      render :new
    end
  end

  def edit

    @wiki = Wiki.friendly.find(params[:id])
    #instance variable of all collaborators on this wiki
    #@collaborators = @wiki.collaborators.map{ |collaborator| collaborator.user }
    @collaborators = @wiki.wiki_collaborators
    #instance variable of all possible collaborators but not the user or current collaborators
    @noncollaborators = User.all - @collaborators - [current_user]

  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Your update was saved correctly!"
      redirect_to [@wiki]
    else
      flash[:alert] = "There was an error when we tried to save it. Try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "The wiki was deleted!"
      redirect_to wikis_path
    else
      flash[:alert] = "Oops! Something happened and we weren't able to delete it."
      render :show
    end
  end

  private
  # Using a private method to encapsulate the permissible parameters
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
      css_class = 'form-group'
      css_class << ' has-error' if errors.any?
      content_tag :div, capture(&block), class: css_class
  end

  def markdown(textArea)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, hard_wrap: true).render(textArea)
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/user_downgrades_helper.rb
module UserDowngradesHelper
end

app/helpers/user_downgradess_helper.rb
module UserDowngradessHelper
end

app/helpers/user_upgrades_helper.rb
module UserUpgradesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class = "row">
  <div class = "charges">
    <div class = "col-md-12">
    <%= form_tag charges_path do %>
       <h2>Upgrade Your Account</h2>
       <p>For only $10.00 you can upgrade your account and receive these benefits:</p>
       <ul>
         <li>Create private wikis</li>
         <li>Edit all wikis</li>
         <li>Get personalized emails</li>
       </ul>
       <p>Upgrade today by clicking the button below.</p>
       <div class="stripe-button-div">
         <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
       </div>
     <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "BLOCIPEDIA", root_path, :class => 'navbar-brand'  %>
      </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Wiki Board", wikis_path, :class => 'nav-link' %></li>
          <li><%= link_to "Create a New Wiki", new_wiki_path, :class => 'nav-link' %></li>
          <!-- <li class="nav-item"><%= link_to "Wiki's Board", wikis_path, :class => 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'About', wikis_path, :class => 'nav-link' %></li> -->
          <!-- <%= link_to 'Wikis Board', wikis_path, :class => 'navbar-link' %>
          <%= link_to 'About', wikis_path, :class => 'navbar-link' %> -->
        </ul>
         <ul class="nav navbar-nav navbar-right">
          <li><p class="sign-in"><% if user_signed_in? %>
            
            <%= current_user.role.capitalize %> Member |
            Signed in as: <strong><%= current_user.email %></strong> | <%= link_to 'Edit profile', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete  %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path %> - <%= link_to "Sign In", new_user_session_path %>
          <% end %></p>
          </li>
        </ul>

    </div>
  </nav>
  <div class = "container">
    <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
    <% end %>


  <!-- <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %> -->

    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  <% end %>

  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter the description of the wiki" %>
  <% end %>

  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.check_box :private %> Private Wiki
  </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki!</h1>
<div class="row">
  <div class="col-md-4">
    <p>Be careful when you are editing wikis.</p>
  </div>
  <div class="col-md-8">
    <%= render partial: "form", locals: { wiki: @wiki } %>
  </div>
  <% if current_user.premium? && @wiki.private %>
  <div class="col-md-4">
    <h2>Collaborators</h2>
    <% @collaborators.each do |collaborators| %>
      <div class="media">
        <div class="media-body">
          <h5 class="media-heading">
              <%= "#{collaborators.email} " %><%= link_to "[remove]", collaborator_path(@wiki, :user_id => collaborators), :action => "create", :method => "delete" %>
          </h5>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Possible Collaborators</h2>
    <% @noncollaborators.each do |noncollaborators| %>
      <div class="media">
        <div class="media-body">
          <h5 class="media-heading">
            <%= "#{noncollaborators.email} " %>
            <%= link_to "[add]", collaborators_path(:wiki_id => @wiki, :user_id => "#{noncollaborators.id}"), :action => "create", :method => "post" %>
          </h5>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to "#{wiki.title}", wiki %>
          <small><%= "[Public]" unless wiki.private %></small>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>Create a new Wiki!</h1>
<div class="row">
  <div class="col-md-4">
    <p>Here is a brief description of some instructions of how the wiki should be created.</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body).html_safe %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-success" %>
    <% end %>
    <%= link_to "Delete", @wiki, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure you want to delete this entry?' } %>
  </div>
</div>